name: reveal_on_pull

description: A package that wraps a scrollable widget and reveals a widget on a pull action.

version: 1.0.3

homepage: https://github.com/manaspratap/reveal_on_pull/blob/main/README.md

repository: https://github.com/manaspratap/reveal_on_pull

issue_tracker: https://github.com/manaspratap/reveal_on_pull/issues

documentation: https://github.com/manaspratap/reveal_on_pull/blob/main/README.md

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: 3.0.0
  test: 1.24.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

screenshots:
  - description: 'This screenshot shows the state where the "widget to reveal" is invisible'
    path: assets/ss_revealed.png
  - description: 'This screenshot shows the state where the "widget to reveal" is visible'
    path: assets/ss_unrevealed.png
